export const wisdoms = [
  // ─── Prophet Muhammad (PBUH) — ~100 quotes ───────────────────────────
  { en: "The best of people are those who are most beneficial to others.", fa: "بهترین مردم کسی است که سودمندترین آنها برای دیگران باشد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Seek knowledge from the cradle to the grave.", fa: "از گهواره تا گور دانش بجوی.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The ink of the scholar is more sacred than the blood of the martyr.", fa: "مرکب دانشمند از خون شهید مقدس‌تر است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A kind word is a form of charity.", fa: "سخن نیکو صدقه است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Make things easy and do not make them difficult, cheer people up and do not scare them away.", fa: "آسان بگیرید و سخت نگیرید، مژده دهید و نفرت نیفکنید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "He who is not merciful to others will not be treated mercifully.", fa: "هر که به دیگران رحم نکند، بر او رحم نخواهد شد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The strong person is not the one who can wrestle someone else down; the strong person is the one who can control himself when he is angry.", fa: "قوی کسی نیست که دیگری را به زمین بزند، قوی کسی است که هنگام خشم خود را کنترل کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "None of you truly believes until he wishes for his brother what he wishes for himself.", fa: "هیچ‌کس ایمان کامل ندارد مگر آنکه برای برادرش همان را بخواهد که برای خود می‌خواهد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best among you are those who have the best character.", fa: "بهترین شما کسانی هستند که اخلاقشان بهتر است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever believes in God and the Last Day, let him speak good or remain silent.", fa: "هر کس به خدا و روز قیامت ایمان دارد، یا سخن نیک بگوید یا سکوت کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Do not waste water even if you are at a running stream.", fa: "اسراف در آب نکنید حتی اگر بر کنار نهر جاری باشید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The world is a prison for the believer and a paradise for the disbeliever.", fa: "دنیا زندان مؤمن و بهشت کافر است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "He who eats his fill while his neighbor goes hungry is not a believer.", fa: "آن که سیر بخوابد و همسایه‌اش گرسنه باشد، مؤمن نیست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Modesty brings nothing except good.", fa: "حیا جز نیکی چیزی نمی‌آورد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best of you are those who learn the Quran and teach it.", fa: "بهترین شما کسی است که قرآن را بیاموزد و آن را بیاموزاند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Richness is not having many possessions, but richness is the richness of the soul.", fa: "ثروتمندی به فراوانی دارایی نیست، بلکه ثروتمندی، بی‌نیازی روح است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The most beloved of deeds to God are those that are most consistent, even if they are small.", fa: "محبوب‌ترین اعمال نزد خداوند آن‌هایی هستند که مداوم باشند، هرچند اندک.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Smiling in the face of your brother is charity.", fa: "لبخند زدن به روی برادرت صدقه است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever is kind, God grants him what He does not grant to those who use harshness.", fa: "هر که مهربان باشد، خداوند به او چیزی عطا می‌کند که به درشت‌خو نمی‌دهد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Every act of goodness is charity.", fa: "هر کار نیکی صدقه است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Pay the worker his wages before his sweat dries.", fa: "مزد کارگر را پیش از خشک شدن عرقش بدهید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "God does not look at your outward appearance or wealth, but at your hearts and deeds.", fa: "خداوند به ظاهر و اموال شما نمی‌نگرد، بلکه به دل‌ها و اعمالتان می‌نگرد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The believers, in their mutual mercy and love, are like a single body; when one limb aches, the whole body responds with sleeplessness and fever.", fa: "مؤمنان در مهر و دوستی مانند یک پیکرند؛ چون عضوی درد گیرد، سراسر بدن بی‌خوابی و تب را حس کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever treads a path in search of knowledge, God will make easy for him a path to Paradise.", fa: "هر که در طلب دانش راهی بپیماید، خداوند راهی به سوی بهشت برایش آسان می‌گرداند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A white person has no superiority over a black person, nor a black over a white, except by piety and good action.", fa: "هیچ سفیدپوستی بر سیاه‌پوستی برتری ندارد و نه سیاه‌پوستی بر سفیدپوستی، مگر به تقوا و عمل نیک.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Removing a harmful thing from the road is charity.", fa: "برداشتن مانع آزاردهنده از سر راه صدقه است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Speak the truth even if it is bitter.", fa: "حقیقت را بگو هرچند تلخ باشد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "He who does not thank people does not thank God.", fa: "هر که از مردم سپاسگزار نباشد، از خدا سپاسگزار نیست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Beware of envy, for envy devours good deeds as fire devours wood.", fa: "از حسد بپرهیزید که حسد نیکی‌ها را می‌خورد همان‌گونه که آتش هیزم را.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The most perfect of believers in faith are those best in character and kindest to their families.", fa: "کامل‌ترین مؤمنان از نظر ایمان کسانی‌اند که اخلاقشان بهتر و با خانواده‌شان مهربان‌ترند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Patience is the key to relief.", fa: "صبر کلید گشایش است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Exchange gifts and you will love one another.", fa: "به یکدیگر هدیه بدهید تا یکدیگر را دوست بدارید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "God is gentle and loves gentleness in all things.", fa: "خداوند مهربان است و مهربانی را در همه چیز دوست دارد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever is not grateful for small things will not be grateful for large things.", fa: "هر که شکر اندک نکند، شکر بسیار نخواهد کرد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best charity is that given in secret.", fa: "بهترین صدقه آن است که پنهانی داده شود.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Take advantage of five before five: your youth before your old age, your health before your sickness, your wealth before your poverty, your free time before your work, and your life before your death.", fa: "پنج چیز را پیش از پنج چیز غنیمت شمار: جوانی را پیش از پیری، تندرستی را پیش از بیماری، توانگری را پیش از تنگدستی، فراغت را پیش از گرفتاری، و زندگی را پیش از مرگ.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A believer is the mirror of his brother; when he sees a fault in him, he corrects it.", fa: "مؤمن آینه مؤمن است؛ وقتی عیبی در او ببیند اصلاحش می‌کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best of houses is the house in which an orphan is well treated.", fa: "بهترین خانه‌ها خانه‌ای است که در آن با یتیمی نیکو رفتار شود.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "If you guarantee me six things on your part, I shall guarantee you Paradise: speak the truth, keep your promises, fulfill your trusts, guard your chastity, lower your gaze, and restrain your hands from injustice.", fa: "اگر شش چیز را تضمین کنید، بهشت را برایتان تضمین می‌کنم: راست بگویید، به وعده وفا کنید، امانت‌دار باشید، پاکدامنی کنید، چشم‌هایتان را حفظ کنید، و دستتان را از ستم بازدارید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "God has no mercy on one who has no mercy for others.", fa: "خداوند بر کسی که به دیگران رحم نکند رحم نمی‌کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Cleanliness is half of faith.", fa: "نظافت نیمی از ایمان است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Feed the hungry, visit the sick, and set free the captives.", fa: "گرسنگان را سیر کنید، بیماران را عیادت کنید و اسیران را آزاد سازید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The merciful are shown mercy by the All-Merciful. Be merciful to those on earth and the One in heaven will be merciful to you.", fa: "مهربانان مورد رحمت خداوند رحمان قرار می‌گیرند. به اهل زمین مهربانی کنید تا آسمانیان به شما مهربانی کنند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Do not be people without minds of your own, saying that if others treat you well you will treat them well and that if they do wrong you will do wrong. Instead, accustom yourselves to do good if people do good, and to not do wrong if they do evil.", fa: "مردمی بی‌اراده نباشید که بگویید اگر مردم نیکی کنند نیکی می‌کنیم و اگر ستم کنند ستم می‌کنیم. بلکه خود را عادت دهید اگر نیکی کردند نیکی کنید و اگر بدی کردند ستم نکنید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The one who plants a tree and patiently waits for it to bear fruit is rewarded for every person and animal that benefits from it.", fa: "هر کس درختی بکارد و صبورانه منتظر ثمرش بماند، از هر انسان و جانوری که از آن بهره‌مند شود پاداش می‌گیرد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Kindness is a mark of faith, and whoever has no kindness has no faith.", fa: "مهربانی نشانه ایمان است و هر که مهربانی ندارد ایمان ندارد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A good word is charity.", fa: "سخن نیکو صدقه است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Acquire knowledge; it enables its possessor to distinguish right from wrong.", fa: "دانش بیاموزید؛ دانش صاحبش را توانا می‌سازد تا درست را از نادرست بازشناسد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever follows a path to seek knowledge, God will make the path to Paradise easy for him.", fa: "هر کس راهی برای جستجوی دانش بپیماید، خداوند راه بهشت را برایش آسان می‌کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Do not belittle any good deed, even meeting your brother with a cheerful face.", fa: "هیچ کار نیکی را کوچک نشمارید، حتی اینکه برادرت را با چهره‌ای خندان ملاقات کنی.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The one who looks after a widow or a poor person is like a warrior who fights for the cause of God.", fa: "آن که از بیوه‌زنی یا فقیری نگهداری کند، مانند مجاهد در راه خداست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "He is not a believer whose stomach is filled while the neighbor beside him goes hungry.", fa: "مؤمن نیست کسی که شکمش سیر باشد و همسایه‌اش گرسنه.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Verily, God does not look at your faces and your wealth, but He looks at your hearts and your deeds.", fa: "همانا خداوند به چهره‌ها و اموال شما نگاه نمی‌کند، بلکه به دل‌ها و اعمالتان نگاه می‌کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "When you see a person who has been given more than you in money and beauty, then look to those who have been given less.", fa: "وقتی کسی را دیدید که مال و زیبایی بیشتری دارد، به کسانی بنگرید که کمتر دارند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The most complete gift of God is a life based on knowledge.", fa: "کامل‌ترین هدیه خداوند زندگی بر پایه دانش است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Part of someone's being a good Muslim is leaving alone that which does not concern him.", fa: "از نشانه‌های مسلمانی نیک آن است که آدمی آنچه به او مربوط نیست واگذارد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A man's true wealth is the good he does in this world.", fa: "ثروت حقیقی انسان نیکی‌هایی است که در این دنیا انجام می‌دهد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "God loves kindness when you deal with any matter.", fa: "خداوند مهربانی را در هر کاری دوست دارد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever is humble for the sake of God, God will elevate him.", fa: "هر که برای خدا فروتنی کند، خداوند او را بالا می‌برد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Actions are judged by their intentions.", fa: "اعمال به نیت‌هاست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "He who has even a grain of pride in his heart shall not enter Paradise.", fa: "کسی که ذره‌ای کبر در دلش باشد وارد بهشت نمی‌شود.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best of charity is when a Muslim gains knowledge, then teaches it to his brother.", fa: "بهترین صدقه آن است که مسلمان دانشی بیاموزد و سپس آن را به برادرش بیاموزاند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "God loves that when you do something, you do it with excellence.", fa: "خداوند دوست دارد که هرگاه کاری انجام می‌دهید آن را نیکو انجام دهید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The hour will not come until knowledge is taken away and ignorance prevails.", fa: "قیامت برپا نمی‌شود تا دانش برداشته شود و نادانی غلبه کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Beware of suspicion, for suspicion is the worst of false tales.", fa: "از بدگمانی بپرهیزید زیرا بدگمانی دروغ‌ترین سخن است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever believes in God and the Last Day should be generous to his neighbor.", fa: "هر که به خدا و روز قیامت ایمان دارد با همسایه‌اش بخشنده باشد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The cure of ignorance is to ask and learn.", fa: "درمان نادانی پرسیدن و آموختن است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Help your brother whether he is an oppressor or is being oppressed—by restraining the oppressor from his oppression.", fa: "برادرت را یاری کن چه ستمگر باشد چه ستمدیده—ستمگر را با بازداشتنش از ستم یاری کن.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Make things easy, not difficult. Give glad tidings, do not drive people away.", fa: "آسان بگیرید و سخت نگیرید. مژده دهید و مردم را نرانید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The most hated speech to God is when one man says to another, 'Fear God!' and he replies, 'Mind your own business!'", fa: "منفورترین سخن نزد خدا آن است که کسی بگوید از خدا بترس و دیگری بگوید به کار خودت برس!", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever restrains his anger, God will conceal his faults.", fa: "هر که خشمش را فرو خورد، خداوند عیب‌هایش را می‌پوشاند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Shall I not inform you of the best of your deeds? It is the remembrance of God.", fa: "آیا شما را به بهترین اعمالتان خبر ندهم؟ یاد خداست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever goes to sleep with a full stomach while his neighbor is hungry has not truly believed in me.", fa: "هر که سیر بخوابد و همسایه‌اش گرسنه باشد به راستی به من ایمان نیاورده است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "God helps the servant as long as the servant helps his brother.", fa: "خداوند بنده را یاری می‌کند تا زمانی که بنده برادرش را یاری می‌کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "He who sleeps with a full stomach knowing that his neighbor is hungry is not one of us.", fa: "آن که سیر بخوابد و بداند همسایه‌اش گرسنه است از ما نیست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A father gives his child nothing better than a good education.", fa: "پدر هیچ هدیه‌ای بهتر از تربیت نیکو به فرزندش نمی‌دهد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Spread peace, feed the hungry, and pray at night when people are sleeping, and you will enter Paradise in peace.", fa: "سلام را بگسترانید، گرسنگان را سیر کنید و در شب هنگامی که مردم در خوابند نماز بگزارید تا به سلامت وارد بهشت شوید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "There is reward for kindness to every living thing.", fa: "در مهربانی با هر موجود زنده‌ای پاداشی هست.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best people are those who are slow to anger and swift to forgive.", fa: "بهترین مردم کسانی‌اند که دیر به خشم آیند و زود ببخشند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A Muslim is one from whose tongue and hand other people are safe.", fa: "مسلمان کسی است که مردم از زبان و دستش در امان باشند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Do not turn away a poor man even if all you can give is half a date.", fa: "فقیری را نومید نکنید حتی اگر تنها نیمی از یک خرما دارید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Strive always to excel in virtue and truth.", fa: "همواره بکوشید در فضیلت و حقیقت پیشگام باشید.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The most perfect believer in faith is the one whose character is finest and who is kindest to his wife.", fa: "کامل‌ایمان‌ترین مؤمن کسی است که خوش‌اخلاق‌ترین باشد و با همسرش مهربان‌تر.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "When a thing disturbs the peace of your heart, give it up.", fa: "هرگاه چیزی آرامش دلت را برهم زد، رهایش کن.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The one who is most beloved to God is the one who is most beneficial to the people.", fa: "محبوب‌ترین بندگان نزد خداوند کسی است که بیشترین سود را به مردم برساند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Deliberation is from God and haste is from Satan.", fa: "تأمل از خداست و شتاب از شیطان.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Seek knowledge even if it be in China.", fa: "دانش را بجویید حتی اگر در چین باشد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "It is better to sit alone than in company with the bad, and it is better to sit with the good than alone.", fa: "تنها نشستن بهتر از همنشینی با بدان است و همنشینی با نیکان بهتر از تنهایی.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Be in this world as if you were a stranger or a traveler.", fa: "در این دنیا چنان باش که گویی غریبی یا رهگذری.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever is deprived of gentleness is deprived of all good.", fa: "هر که از نرمی محروم شود از همه خیر محروم شده است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Tie your camel and trust in God.", fa: "شترت را ببند و بر خدا توکل کن.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best of companions in the sight of God is the one who is best to his companions.", fa: "بهترین یاران نزد خدا کسی است که با یارانش بهتر رفتار کند.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Whoever has three things discovers the sweetness of faith: love of God and His Messenger above all else, love of another only for God's sake, and hatred to return to disbelief as one hates to be thrown into fire.", fa: "هر که سه چیز داشته باشد شیرینی ایمان را می‌یابد: دوست داشتن خدا و پیامبرش بیش از هر چیز، دوست داشتن دیگری تنها به خاطر خدا، و بیزاری از بازگشت به کفر همچون بیزاری از افکنده شدن در آتش.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The upper hand is better than the lower hand. The upper hand is the one that gives, and the lower hand is the one that takes.", fa: "دست بالا بهتر از دست پایین است. دست بالا دست بخشنده است و دست پایین دست گیرنده.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Verily, with hardship there is relief.", fa: "همانا با سختی آسانی است.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "A woman asked me, 'How do I know my prayer is accepted?' I said, 'If it keeps you from wrongdoing.'", fa: "زنی پرسید: چگونه بدانم نمازم پذیرفته شده؟ گفتم: اگر تو را از بدی باز دارد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The world is green and sweet, and God has made you stewards in it.", fa: "دنیا سبز و شیرین است و خداوند شما را جانشینان خود در آن قرار داده.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Leave that which makes you doubt for that which does not make you doubt.", fa: "آنچه تو را به شک می‌اندازد رها کن و به آنچه شک نداری روی آور.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "Do not be angry, and Paradise is yours.", fa: "خشمگین نشو تا بهشت از آن تو باشد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },
  { en: "The best of journeys is the one that takes you to the house of God.", fa: "بهترین سفرها آن است که تو را به خانه خدا ببرد.", author: "Prophet Muhammad (PBUH)", authorFa: "پیامبر اکرم (ص)" },

  // ─── Ali ibn Abi Talib — ~80 quotes ──────────────────────────────────
  { en: "The tongue is a beast; if it is let loose, it devours.", fa: "زبان درنده‌ای است که اگر رها شود می‌درد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Patience is of two kinds: patience over what pains you, and patience against what you covet.", fa: "صبر دو گونه است: صبر بر آنچه ناگوار است و صبر در برابر آنچه دوست داری.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The worth of a man lies in what he does well.", fa: "ارزش هر کسی به اندازه کاری است که نیکو انجام می‌دهد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Do not let your difficulties fill you with anxiety; after all, it is only in the darkest nights that stars shine more brightly.", fa: "مگذار سختی‌ها تو را مضطرب کند، ستارگان در تاریک‌ترین شب‌ها درخشان‌ترند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A wise man first thinks and then speaks; a fool speaks first and then thinks.", fa: "انسان دانا نخست می‌اندیشد و سپس سخن می‌گوید، اما نادان نخست سخن می‌گوید و سپس می‌اندیشد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Your remedy is within you, but you do not sense it.", fa: "درمان تو در درون توست اما احساسش نمی‌کنی.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "People are enemies of what they do not know.", fa: "مردم دشمن چیزی هستند که نمی‌دانند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Knowledge is better than wealth; knowledge guards you while you must guard wealth.", fa: "دانش بهتر از ثروت است؛ دانش تو را نگهبان است و ثروت را تو باید نگهبانی کنی.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Detachment is not that you should own nothing, but that nothing should own you.", fa: "زهد آن نیست که چیزی نداشته باشی، بلکه آن است که چیزی تو را نداشته باشد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The best deed of a great man is to forgive and forget.", fa: "بهترین کار یک بزرگمرد بخشیدن و فراموش کردن است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who has a thousand friends has not a friend to spare, and he who has one enemy will meet him everywhere.", fa: "آن‌که هزار دوست دارد یک دوست اضافی ندارد و آن‌که یک دشمن دارد همه‌جا او را می‌بیند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Do not raise your children the way your parents raised you; they were born for a different time.", fa: "فرزندانتان را مانند خودتان تربیت نکنید؛ آنها برای زمانی دیگر آفریده شده‌اند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Silence is the best reply to a fool.", fa: "سکوت بهترین پاسخ به نادان است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Fear the sins that you commit in secret, because the Witness of those sins is the Judge Himself.", fa: "از گناهانی که در خلوت مرتکب می‌شوی بترس، زیرا شاهد آن گناهان خود داور است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Stubbornness destroys good counsel.", fa: "لجاجت رأی درست را نابود می‌کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "If you love God, tear out your heart's love of the world.", fa: "اگر خدا را دوست داری، عشق دنیا را از دلت بیرون کن.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A man's measure is his will.", fa: "اندازه هر انسانی همت اوست.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The one who puts himself in the position of suspicion should not blame those who think badly of him.", fa: "آن‌که خود را در جایگاه تهمت قرار دهد نباید بدگمانان را سرزنش کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Be like the flower that gives its fragrance to even the hand that crushes it.", fa: "مانند گلی باش که حتی به دستی که لِهَش می‌کند عطر می‌بخشد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The wealthiest of people is the one who is not a prisoner to greed.", fa: "ثروتمندترین مردم کسی است که اسیر طمع نباشد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who trusts the world, the world betrays him.", fa: "هر که به دنیا اعتماد کند، دنیا خیانتش می‌کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Forgiveness is the crown of greatness.", fa: "بخشش تاج بزرگی است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "One who rushes headlong into things will also rush headlong into mistakes.", fa: "آن‌که شتاب‌زده وارد کارها شود، شتاب‌زده به خطا نیز می‌افتد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Associating with the wise will add to your wisdom.", fa: "همنشینی با خردمندان بر خرد تو می‌افزاید.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The greatest wealth is wisdom; the greatest poverty is ignorance.", fa: "بزرگ‌ترین ثروت خرد است و بزرگ‌ترین فقر نادانی.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A friend cannot be considered a friend until he is tested in three occasions: in time of need, behind your back, and after your death.", fa: "دوست واقعی کسی نیست مگر آنکه در سه موقعیت آزموده شود: هنگام نیاز، پشت سرت، و پس از مرگت.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "How strange and foolish is man: he loses his health in gaining wealth, then loses his wealth in trying to regain his health.", fa: "چه عجیب و نادان است انسان: سلامتش را در کسب ثروت از دست می‌دهد، سپس ثروتش را برای بازیابی سلامت.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The one who has no patience has no faith.", fa: "آنکه صبر ندارد ایمان ندارد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A moment of patience in a moment of anger prevents a thousand moments of regret.", fa: "لحظه‌ای صبر در لحظه‌ای خشم، هزار لحظه پشیمانی را دور می‌کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The nourishment of the body is food, while the nourishment of the soul is feeding others.", fa: "خوراک بدن غذاست و خوراک روح، سیر کردن دیگران.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Through patience, great things are accomplished.", fa: "با صبر، کارهای بزرگ به انجام می‌رسد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A man's intellect is revealed by what he says; his nature by what he does.", fa: "عقل انسان از گفتارش آشکار می‌شود و سرشتش از کردارش.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Do for this world as if you will live forever, and do for the next as if you will die tomorrow.", fa: "برای دنیا چنان کار کن که گویی جاودان زنده‌ای و برای آخرت چنان که گویی فردا می‌میری.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who busies himself with things other than improvement of his own self becomes perplexed.", fa: "آنکه به چیزی جز اصلاح خویش مشغول شود سرگردان گردد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Courtesy costs nothing but buys everything.", fa: "ادب هزینه‌ای ندارد اما همه چیز می‌خرد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Take from the world only what is sufficient, and leave the rest.", fa: "از دنیا فقط به اندازه کفایت بردار و بقیه را رها کن.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Hearts of people are like wild birds; they are captured by those who scatter crumbs.", fa: "دل‌های مردم مانند پرندگان وحشی‌اند؛ با نیکی شکار می‌شوند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Greed is permanent slavery.", fa: "طمع بردگی همیشگی است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The best speech is that which is short and makes the point.", fa: "بهترین سخن آن است که کوتاه باشد و مقصود را برساند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Protect your tongue as you protect your gold and silver.", fa: "زبانت را نگه‌دار همان‌گونه که طلا و نقره‌ات را نگه می‌داری.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The disease of the heart is worse than the disease of the body.", fa: "بیماری دل بدتر از بیماری بدن است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Whoever educates himself and improves his own morals is superior to the man who tries to teach and train others.", fa: "هرکه خود را تربیت کند و اخلاقش را بهبود بخشد برتر است از کسی که دیگران را پند می‌دهد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A person's true wealth is the good they do in the world.", fa: "ثروت واقعی انسان نیکی‌هایی است که در جهان انجام می‌دهد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Live among people in such a manner that if you die they weep over you, and if you are alive they crave your company.", fa: "چنان در میان مردم زندگی کن که اگر مُردی بر تو بگریند و اگر زنده‌ای مشتاق همنشینی‌ات باشند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The learned live after death; the ignorant are dead while still alive.", fa: "دانایان پس از مرگ زنده‌اند و نادانان در زندگی مرده‌اند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "No wealth is more useful than intelligence.", fa: "هیچ ثروتی سودمندتر از عقل نیست.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who cannot control his desires cannot control his dignity.", fa: "آنکه نمی‌تواند خواهش‌هایش را مهار کند، عزتش را نمی‌تواند حفظ کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Not every person who gives you counsel has your best interest at heart.", fa: "هرکسی که به تو نصیحت می‌کند لزوماً خیرخواه تو نیست.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Beware of the flight of blessings, for nothing that runs away is ever brought back.", fa: "مراقب گریختن نعمت‌ها باش، زیرا هیچ‌چیز گریخته‌ای بازنمی‌گردد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The tongue is like a lion: if you let it loose, it will wound someone.", fa: "زبان مانند شیر است: اگر رهایش کنی کسی را زخمی خواهد کرد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "When wisdom reaches its peak, speech becomes less.", fa: "چون خرد به اوج رسد، سخن کم می‌شود.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Lose your wealth and save your soul.", fa: "مال را از دست بده و جان را نجات بخش.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "If you want to know a man's character, give him authority.", fa: "اگر می‌خواهی سرشت کسی را بشناسی، به او قدرت بده.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The sin that makes you sad and repentant is more liked by God than the good deed that turns you arrogant.", fa: "گناهی که تو را غمگین و توبه‌کار سازد نزد خدا محبوب‌تر است از عمل نیکی که تو را متکبر کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "When the world pushes you to your knees, you're in the perfect position to pray.", fa: "وقتی دنیا تو را به زانو درآورد، در بهترین حالت برای دعا کردن هستی.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Do not be a slave to others when God has created you free.", fa: "بنده دیگران نباش وقتی خداوند تو را آزاد آفریده.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Beautiful patience is patience without complaint.", fa: "صبر زیبا آن صبری است که بدون شکایت باشد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The most helpless person is the one who cannot find a few brothers during his life, and even more helpless is the one who loses those he found.", fa: "درمانده‌ترین کس آن‌که در طول عمرش چند دوست نیابد، و درمانده‌تر آن‌که آنان را که یافته از دست بدهد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Nothing hurts a good soul and a kind heart more than living among people who do not understand.", fa: "هیچ‌چیز روح پاک و دل مهربان را بیشتر از زیستن در میان مردمی که نمی‌فهمند نمی‌آزارد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "An ignorant person is one who is the enemy of himself; how can he be a friend to others?", fa: "نادان کسی است که دشمن خویش است؛ چگونه می‌تواند دوست دیگران باشد؟", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Knowledge enlivens the soul.", fa: "دانش جان را زنده می‌کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The highest degree of wisdom is self-knowledge.", fa: "بالاترین درجه خرد، خودشناسی است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "A man who tries to impress others will lose all true merit.", fa: "آنکه بکوشد دیگران را تحت تأثیر قرار دهد همه ارزش حقیقی را از دست خواهد داد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Opportunity passes like a cloud; so make use of good opportunities.", fa: "فرصت مانند ابر می‌گذرد، پس فرصت‌های نیک را غنیمت شمار.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Generosity hides shortcomings.", fa: "بخشندگی عیب‌ها را می‌پوشاند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The one who remembers death is satisfied with a little in this world.", fa: "آنکه مرگ را به یاد دارد از اندکی در دنیا خشنود است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who shows no gratitude to man shows no gratitude to God.", fa: "آنکه از مردم سپاسگزار نباشد از خدا سپاسگزار نیست.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Meet people in such a manner that if you die they should weep for you, and if you live they should long for you.", fa: "با مردم چنان رفتار کن که اگر مُردی بر تو بگریند و اگر زنده‌ای مشتاقت باشند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Authority reveals a person's true nature.", fa: "قدرت، ذات واقعی انسان را آشکار می‌کند.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Anger begins with madness and ends with regret.", fa: "خشم با دیوانگی آغاز و با پشیمانی پایان می‌یابد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Justice is the foundation of governance.", fa: "عدالت بنیاد حکومت است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who overcomes his desires is braver than he who conquers his enemies.", fa: "آنکه بر خواهش‌هایش چیره شود شجاع‌تر از کسی است که دشمنانش را شکست دهد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Wealth diminishes by spending, but knowledge is enriched by use.", fa: "ثروت با خرج کردن کم می‌شود اما دانش با به‌کار بردن غنی‌تر می‌گردد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Do not be the slave of another person, for God has created you free.", fa: "بنده دیگری نباش که خداوند تو را آزاد آفریده است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who abandons his friends will have no share in generosity.", fa: "آنکه دوستانش را ترک کند بهره‌ای از بزرگواری ندارد.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "He who has an opinion of his own but holds to that of another is a slave.", fa: "آنکه رأی خود دارد اما رأی دیگری را پیروی کند بنده است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "If poverty were a man, I would have killed him.", fa: "اگر فقر مردی بود، او را می‌کشتم.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The peak of wisdom is to fear God.", fa: "اوج خردمندی ترس از خداست.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "Be generous but not extravagant; be thrifty but not miserly.", fa: "سخاوتمند باش اما اسراف‌کار نه؛ صرفه‌جو باش اما خسیس نه.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },
  { en: "The best form of worship is contemplation.", fa: "بهترین عبادت تفکر است.", author: "Ali ibn Abi Talib", authorFa: "علی ابن ابی‌طالب" },

  // ─── Rumi — ~70 quotes ───────────────────────────────────────────────
  { en: "Let yourself be silently drawn by the strange pull of what you really love.", fa: "بگذار آنچه را واقعاً دوست داری بی‌صدا تو را به سوی خود بکشاند.", author: "Rumi", authorFa: "مولانا" },
  { en: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", fa: "دیروز عاقل بودم و می‌خواستم دنیا را عوض کنم. امروز دانا هستم و خودم را تغییر می‌دهم.", author: "Rumi", authorFa: "مولانا" },
  { en: "The wound is the place where the Light enters you.", fa: "زخم جایی است که نور به درون تو راه می‌یابد.", author: "Rumi", authorFa: "مولانا" },
  { en: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", fa: "کلامت را بالا ببر نه صدایت را. این باران است که گل می‌رویاند نه رعد.", author: "Rumi", authorFa: "مولانا" },
  { en: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", fa: "آن سوی نیکی و بدی صحرایی است، من تو را آنجا ملاقات خواهم کرد.", author: "Rumi", authorFa: "مولانا" },
  { en: "Don't grieve. Anything you lose comes round in another form.", fa: "غم نخور. هر آنچه از دست بدهی به شکلی دیگر بازمی‌گردد.", author: "Rumi", authorFa: "مولانا" },
  { en: "The only lasting beauty is the beauty of the heart.", fa: "تنها زیبایی ماندگار، زیبایی دل است.", author: "Rumi", authorFa: "مولانا" },
  { en: "What you seek is seeking you.", fa: "آنچه در جستجویش هستی در جستجوی توست.", author: "Rumi", authorFa: "مولانا" },
  { en: "Silence is the language of God; all else is poor translation.", fa: "سکوت زبان خداست؛ هر چه جز آن ترجمه‌ای ناقص است.", author: "Rumi", authorFa: "مولانا" },
  { en: "Where there is ruin, there is hope for treasure.", fa: "هر کجا ویرانه‌ای هست، امید گنجی نهفته است.", author: "Rumi", authorFa: "مولانا" },
  { en: "You were born with wings; why prefer to crawl through life?", fa: "با بال‌ها زاده شدی؛ چرا ترجیح می‌دهی در زندگی بخزی؟", author: "Rumi", authorFa: "مولانا" },
  { en: "Love is the bridge between you and everything.", fa: "عشق پلی است میان تو و همه چیز.", author: "Rumi", authorFa: "مولانا" },
  { en: "Be like a tree, and let the dead leaves drop.", fa: "مانند درخت باش و بگذار برگ‌های مرده بیفتند.", author: "Rumi", authorFa: "مولانا" },
  { en: "There is a voice that doesn't use words. Listen.", fa: "آوایی هست که از واژه‌ها بهره نمی‌برد. گوش بده.", author: "Rumi", authorFa: "مولانا" },
  { en: "Set your life on fire. Seek those who fan your flames.", fa: "زندگی‌ات را آتش بزن. جویای کسانی باش که شعله‌هایت را برافروزند.", author: "Rumi", authorFa: "مولانا" },
  { en: "Everything that is made beautiful and fair and lovely is made for the eye of the one who sees.", fa: "هرچه زیبا و دلپسند آفریده شده برای چشمی است که می‌بیند.", author: "Rumi", authorFa: "مولانا" },
  { en: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", fa: "کار تو جستجوی عشق نیست بلکه یافتن تمام موانعی است که در درون خود در برابر آن ساخته‌ای.", author: "Rumi", authorFa: "مولانا" },
  { en: "Let the beauty of what you love be what you do.", fa: "بگذار زیبایی آنچه دوست داری همان باشد که انجام می‌دهی.", author: "Rumi", authorFa: "مولانا" },
  { en: "Don't be satisfied with stories of how things have gone with others. Unfold your own myth.", fa: "به داستان دیگران بسنده نکن. افسانه خویش را بگشا.", author: "Rumi", authorFa: "مولانا" },
  { en: "Respond to every call that excites your spirit.", fa: "به هر ندایی که روحت را برمی‌انگیزد پاسخ بده.", author: "Rumi", authorFa: "مولانا" },
  { en: "Do not feel lonely. The entire universe is inside you.", fa: "احساس تنهایی نکن. تمام هستی در درون توست.", author: "Rumi", authorFa: "مولانا" },
  { en: "The garden of the world has no limits, except in your mind.", fa: "باغ جهان حد و مرزی ندارد جز در ذهن تو.", author: "Rumi", authorFa: "مولانا" },
  { en: "Why do you stay in prison when the door is so wide open?", fa: "چرا در زندان می‌مانی وقتی در چنین باز است؟", author: "Rumi", authorFa: "مولانا" },
  { en: "Goodbyes are only for those who love with their eyes; those who love with their soul have no goodbye.", fa: "وداع تنها برای کسانی است که با چشم دوست می‌دارند؛ آنان که با جان عشق می‌ورزند وداعی ندارند.", author: "Rumi", authorFa: "مولانا" },
  { en: "In each moment the fire rages, it will burn away a hundred veils. And carry you a thousand steps toward your goal.", fa: "در هر لحظه‌ای که آتش می‌افروزد صد پرده را می‌سوزاند و تو را هزار گام به سوی مقصدت می‌برد.", author: "Rumi", authorFa: "مولانا" },
  { en: "Be grateful for whoever comes, because each has been sent as a guide from beyond.", fa: "از هرکه می‌آید سپاسگزار باش، زیرا هر یک راهنمایی از آن سوست.", author: "Rumi", authorFa: "مولانا" },
  { en: "Patience is not sitting and waiting; it is foreseeing. It is looking at the thorn and seeing the rose.", fa: "صبر نشستن و انتظار کشیدن نیست؛ پیش‌بینی کردن است. خار را نگاه کردن و گل را دیدن است.", author: "Rumi", authorFa: "مولانا" },
  { en: "Be empty of worrying. Think of who created thought.", fa: "از نگرانی تهی باش. بیندیش که اندیشه را چه کسی آفرید.", author: "Rumi", authorFa: "مولانا" },
  { en: "In your light I learn how to love. In your beauty, how to make poems. You dance inside my chest where no one sees you.", fa: "در نور تو عاشقی آموختم. در زیبایی‌ات شعرگویی. تو در سینه‌ام می‌رقصی آنجا که کسی نمی‌بیندت.", author: "Rumi", authorFa: "مولانا" },
  { en: "Lovers don't finally meet somewhere. They're in each other all along.", fa: "عاشقان سرانجام جایی یکدیگر را نمی‌یابند. آنها از آغاز در یکدیگرند.", author: "Rumi", authorFa: "مولانا" },
  { en: "The morning breeze has secrets to tell you. Do not go back to sleep.", fa: "نسیم صبحگاهی رازهایی دارد که بگوید. دوباره نخواب.", author: "Rumi", authorFa: "مولانا" },
  { en: "I have lived on the lip of insanity, wanting to know reasons, knocking on a door. It opens. I've been knocking from the inside.", fa: "بر لب دیوانگی زیسته‌ام، دلیل‌خواه بر دری می‌کوبیدم. باز شد. از درون می‌کوبیده‌ام.", author: "Rumi", authorFa: "مولانا" },
  { en: "You are not a drop in the ocean. You are the entire ocean in a drop.", fa: "تو قطره‌ای در اقیانوس نیستی. تو تمام اقیانوس در یک قطره‌ای.", author: "Rumi", authorFa: "مولانا" },
  { en: "The soul has been given its own ears to hear things the mind does not understand.", fa: "به روح گوش‌هایی داده شده برای شنیدن چیزهایی که ذهن نمی‌فهمد.", author: "Rumi", authorFa: "مولانا" },
  { en: "When I am silent, I have thunder hidden inside.", fa: "چون خاموش می‌شوم رعدی در درونم نهفته است.", author: "Rumi", authorFa: "مولانا" },
  { en: "Wear gratitude like a cloak and it will feed every corner of your life.", fa: "شکرگزاری را مانند ردایی بپوش تا هر گوشه زندگی‌ات را سیراب کند.", author: "Rumi", authorFa: "مولانا" },
  { en: "Close your eyes, fall in love, stay there.", fa: "چشم‌هایت را ببند، عاشق شو، همان‌جا بمان.", author: "Rumi", authorFa: "مولانا" },
  { en: "Stop acting so small. You are the universe in ecstatic motion.", fa: "دست از کوچک بودن بردار. تو جهانی در حرکت سرمستانه‌ای.", author: "Rumi", authorFa: "مولانا" },
  { en: "Ignore those that make you fearful and sad. That degrade you back towards disease and death.", fa: "از آنان بگریز که تو را ترسان و غمگین می‌سازند و تو را به سوی بیماری و مرگ می‌کشانند.", author: "Rumi", authorFa: "مولانا" },
  { en: "Wherever you are, and whatever you do, be in love.", fa: "هر جا که هستی و هرکاری می‌کنی، عاشق باش.", author: "Rumi", authorFa: "مولانا" },
  { en: "My soul is from elsewhere, I'm sure of that, and I intend to end up there.", fa: "روحم از جای دیگری است، بر آن یقین دارم، و قصد دارم سرانجام بدان‌جا بازگردم.", author: "Rumi", authorFa: "مولانا" },
  { en: "I am not this hair, I am not this skin, I am the soul that lives within.", fa: "من این مو نیستم، من این پوست نیستم، من آن جانم که در درون زندگی می‌کند.", author: "Rumi", authorFa: "مولانا" },
  { en: "This is love: to fly toward a secret sky, to cause a hundred veils to fall each moment.", fa: "عشق همین است: به سوی آسمانی نهان پرواز کنی و هر لحظه صد پرده بیندازی.", author: "Rumi", authorFa: "مولانا" },
  { en: "Sorrow prepares you for joy. It violently sweeps everything out of your house so that new joy can find space to enter.", fa: "اندوه تو را برای شادی آماده می‌سازد. خانه‌ات را با خشونت جارو می‌کند تا شادی تازه جایی برای ورود بیابد.", author: "Rumi", authorFa: "مولانا" },
  { en: "The minute I heard my first love story, I started looking for you, not knowing how blind that was.", fa: "همان لحظه‌ای که نخستین داستان عشق را شنیدم، به جستجوی تو آمدم، ندانسته که چقدر نابینا بودم.", author: "Rumi", authorFa: "مولانا" },
  { en: "Let yourself be drawn by the stronger pull of that which you truly love.", fa: "بگذار جذبه نیرومندتر آنچه واقعاً دوست داری تو را بکشاند.", author: "Rumi", authorFa: "مولانا" },
  { en: "Every moment I shape my destiny with a chisel; I am the carpenter of my own soul.", fa: "هر لحظه سرنوشتم را با تیشه‌ای می‌تراشم؛ نجّار جان خویشم.", author: "Rumi", authorFa: "مولانا" },
  { en: "If you are irritated by every rub, how will your mirror be polished?", fa: "اگر از هر سایشی آزرده شوی، آینه‌ات چگونه صیقل خواهد یافت؟", author: "Rumi", authorFa: "مولانا" },
  { en: "Study me as much as you like; you will never know me. For I differ a hundred ways from what you see me to be.", fa: "هرچه بخواهی مرا بشناس؛ هرگز نخواهی شناخت. زیرا صد فرسنگ با آنچه می‌بینی فاصله دارم.", author: "Rumi", authorFa: "مولانا" },
  { en: "In the blackest of your moments, wait with no fear.", fa: "در سیاه‌ترین لحظه‌هایت بی‌هراس صبر کن.", author: "Rumi", authorFa: "مولانا" },
  { en: "Half-heartedness doesn't reach into majesty.", fa: "دل‌سردی به عظمت نمی‌رسد.", author: "Rumi", authorFa: "مولانا" },
  { en: "There are a thousand ways to kneel and kiss the ground.", fa: "هزار راه هست برای زانو زدن و زمین را بوسیدن.", author: "Rumi", authorFa: "مولانا" },
  { en: "Be like melting snow — wash yourself of yourself.", fa: "مانند برف آب‌شونده باش — خود را از خود بشوی.", author: "Rumi", authorFa: "مولانا" },
  { en: "Words are a pretext. It is the inner bond that draws one person to another, not words.", fa: "کلمات بهانه‌اند. این پیوند درونی است که آدمی را به آدمی می‌کشاند نه کلمات.", author: "Rumi", authorFa: "مولانا" },
  { en: "Whatever lifts the corners of your mouth, trust that.", fa: "هرچه گوشه لب‌هایت را بالا می‌برد، به آن اعتماد کن.", author: "Rumi", authorFa: "مولانا" },
  { en: "These pains you feel are messengers. Listen to them.", fa: "این دردهایی که حس می‌کنی پیام‌آورند. به آنها گوش بسپار.", author: "Rumi", authorFa: "مولانا" },
  { en: "Start a huge, foolish project, like Noah. It makes absolutely no difference what people think of you.", fa: "کاری عظیم و دیوانه‌وار آغاز کن، مانند نوح. هیچ اهمیتی ندارد مردم درباره‌ات چه فکر می‌کنند.", author: "Rumi", authorFa: "مولانا" },
  { en: "When you do things from your soul, you feel a river moving in you, a joy.", fa: "وقتی از جان کاری می‌کنی رودخانه‌ای در درونت جاری می‌شود، شادمانه.", author: "Rumi", authorFa: "مولانا" },
  { en: "Travel brings power and love back into your life.", fa: "سفر، نیرو و عشق را به زندگی‌ات بازمی‌گرداند.", author: "Rumi", authorFa: "مولانا" },
  { en: "That which is false troubles the heart, but truth brings joyous tranquility.", fa: "آنچه دروغین است دل را می‌آشوبد، اما حقیقت آرامشی شادمانه به ارمغان می‌آورد.", author: "Rumi", authorFa: "مولانا" },
  { en: "Sell your cleverness and buy bewilderment.", fa: "زیرکی‌ات را بفروش و حیرت بخر.", author: "Rumi", authorFa: "مولانا" },
  { en: "The lamps are different, but the Light is the same.", fa: "چراغ‌ها گوناگونند، اما نور یکی است.", author: "Rumi", authorFa: "مولانا" },
  { en: "Only from the heart can you touch the sky.", fa: "تنها از دل می‌توان آسمان را لمس کرد.", author: "Rumi", authorFa: "مولانا" },
  { en: "Your heart knows the way. Run in that direction.", fa: "دلت راه را می‌داند. در آن سو بدو.", author: "Rumi", authorFa: "مولانا" },
  { en: "Dance until you shatter yourself.", fa: "برقص تا خود را در هم بشکنی.", author: "Rumi", authorFa: "مولانا" },
  { en: "When the soul lies down in that grass, the world is too full to talk about.", fa: "وقتی جان در آن سبزه می‌آرمد، جهان از بس پُر است، سخن گفتنش ممکن نیست.", author: "Rumi", authorFa: "مولانا" },
  { en: "Forget safety. Live where you fear to live.", fa: "امنیت را فراموش کن. آنجا زندگی کن که می‌ترسی زندگی کنی.", author: "Rumi", authorFa: "مولانا" },
  { en: "A candle never loses any of its light while lighting another candle.", fa: "شمع هیچ‌گاه از نورش نمی‌کاهد وقتی شمع دیگری را روشن می‌کند.", author: "Rumi", authorFa: "مولانا" },
  { en: "As you start to walk on the way, the way appears.", fa: "همین‌که در راه قدم بگذاری، راه پدیدار می‌شود.", author: "Rumi", authorFa: "مولانا" },
  { en: "We come spinning out of nothingness, scattering stars like dust.", fa: "از نیستی می‌آییم چرخان، ستارگان را چون غبار می‌پراکنیم.", author: "Rumi", authorFa: "مولانا" },

  // ─── Saadi — ~30 quotes ──────────────────────────────────────────────
  { en: "Human beings are members of a whole, in creation of one essence and soul.", fa: "بنی‌آدم اعضای یکدیگرند / که در آفرینش ز یک گوهرند.", author: "Saadi", authorFa: "سعدی" },
  { en: "A thankful person is thankful under all circumstances.", fa: "آدم شاکر در همه حال شکرگزار است.", author: "Saadi", authorFa: "سعدی" },
  { en: "Whoever is indifferent to the suffering of others is not worthy to be called human.", fa: "هر که بر درد دیگران بی‌تفاوت باشد، شایسته نام انسان نیست.", author: "Saadi", authorFa: "سعدی" },
  { en: "When one member is afflicted with pain, other members uneasy will remain.", fa: "چو عضوی به درد آورد روزگار / دگر عضوها را نماند قرار.", author: "Saadi", authorFa: "سعدی" },
  { en: "A learned man who doesn't restrain his passions is like a blind man holding a torch: he guides others but not himself.", fa: "دانایی که خواهش‌هایش را مهار نکند مانند نابینایی است که مشعل در دست دارد: دیگران را راهنماست ولی خودش را نه.", author: "Saadi", authorFa: "سعدی" },
  { en: "Have patience; all things are difficult before they become easy.", fa: "صبور باش؛ همه چیز دشوار است پیش از آنکه آسان شود.", author: "Saadi", authorFa: "سعدی" },
  { en: "A rose, though its petals fall, still retains its fragrance.", fa: "گل اگر چه برگش بریزد، عطرش باقی می‌ماند.", author: "Saadi", authorFa: "سعدی" },
  { en: "Nothing is so good for an ignorant man as silence.", fa: "هیچ‌چیز برای نادان بهتر از سکوت نیست.", author: "Saadi", authorFa: "سعدی" },
  { en: "The best way to repay a kindness is to never forget it.", fa: "بهترین راه جبران مهربانی این است که هرگز فراموشش نکنی.", author: "Saadi", authorFa: "سعدی" },
  { en: "Whoever acquires knowledge and does not practice it is like one who plows a field but does not sow it.", fa: "هرکه دانش بیاموزد و عمل نکند مانند کسی است که زمین شخم بزند ولی تخم نکارد.", author: "Saadi", authorFa: "سعدی" },
  { en: "Ten persons who speak make more noise than ten thousand who are silent.", fa: "ده نفر سخنگو بیشتر از ده‌هزار خاموش سر و صدا دارند.", author: "Saadi", authorFa: "سعدی" },
  { en: "A man is insensible to the relish of prosperity until he has tasted adversity.", fa: "آدمی لذت خوشبختی را نمی‌چشد مگر آنکه بلا چشیده باشد.", author: "Saadi", authorFa: "سعدی" },
  { en: "The generous man enriches himself by giving; the miser hoards himself into poverty.", fa: "بخشنده با بخشش خود را غنی می‌کند؛ بخیل با انباشتن خود را فقیر.", author: "Saadi", authorFa: "سعدی" },
  { en: "Every leaf of the tree becomes a page of the book once the heart is opened.", fa: "هر برگ درخت، صفحه‌ای از کتاب می‌شود وقتی دل گشوده شود.", author: "Saadi", authorFa: "سعدی" },
  { en: "If a gem falls into mud, it is still valuable. If dust ascends to heaven, it is still worthless.", fa: "اگر گوهری در گِل افتد همچنان گرانبهاست. اگر خاکی به آسمان رود همچنان بی‌ارزش است.", author: "Saadi", authorFa: "سعدی" },
  { en: "Better to be a free dog than a caged lion.", fa: "سگ آزاد بودن بهتر از شیر در قفس بودن است.", author: "Saadi", authorFa: "سعدی" },
  { en: "The wise man speaks of what he sees, the fool of what he hears.", fa: "خردمند از آنچه می‌بیند سخن می‌گوید، نادان از آنچه می‌شنود.", author: "Saadi", authorFa: "سعدی" },
  { en: "He who is a friend to all is a friend to none.", fa: "آنکه دوست همه است، دوست هیچ‌کس نیست.", author: "Saadi", authorFa: "سعدی" },
  { en: "He who knows not and knows not that he knows not is a fool; shun him.", fa: "آنکه نمی‌داند و نمی‌داند که نمی‌داند نادان است؛ از او دوری کن.", author: "Saadi", authorFa: "سعدی" },
  { en: "A hundred years of tyranny by the sultan is better than one year of tyranny by the people over each other.", fa: "صد سال ستم سلطان بهتر از یک سال ستم مردم بر یکدیگر.", author: "Saadi", authorFa: "سعدی" },
  { en: "I fear God and after God I fear him who fears not God.", fa: "از خدا می‌ترسم و پس از خدا از کسی که از خدا نمی‌ترسد.", author: "Saadi", authorFa: "سعدی" },
  { en: "If you wish to be loved, love.", fa: "اگر خواهی که دوستت بدارند، دوست بدار.", author: "Saadi", authorFa: "سعدی" },
  { en: "Riches are not from an abundance of worldly goods, but from a contented mind.", fa: "توانگری از فراوانی مال دنیا نیست بلکه از قناعت روح است.", author: "Saadi", authorFa: "سعدی" },
  { en: "An enemy who tells the truth is better than a friend who lies.", fa: "دشمنی که راست بگوید بهتر از دوستی است که دروغ بگوید.", author: "Saadi", authorFa: "سعدی" },
  { en: "You who are not affected by another's suffering do not deserve to be called human.", fa: "تو که از رنج دیگران بی‌غمی نشاید که نامت نهند آدمی.", author: "Saadi", authorFa: "سعدی" },
  { en: "However much you study, you cannot know without action. A donkey laden with books is neither an intellectual nor a wise man.", fa: "هرچه بخوانی بی‌عمل عالم نیستی. خری که بار کتاب کشد نه فاضل است نه دانا.", author: "Saadi", authorFa: "سعدی" },
  { en: "The tree which bears fruit bows its head down.", fa: "درختی که میوه دارد سر فرو می‌آورد.", author: "Saadi", authorFa: "سعدی" },
  { en: "Silence is a fence around wisdom.", fa: "سکوت حصاری است پیرامون خرد.", author: "Saadi", authorFa: "سعدی" },
  { en: "A stone thrown at the right time is better than gold given at the wrong time.", fa: "سنگی به وقت بهتر از طلایی بی‌وقت.", author: "Saadi", authorFa: "سعدی" },
  { en: "A lamp has no light of its own; it draws its light from the flame.", fa: "چراغ از خود نوری ندارد؛ نورش را از شعله می‌گیرد.", author: "Saadi", authorFa: "سعدی" },

  // ─── Hafiz — ~25 quotes ──────────────────────────────────────────────
  { en: "I wish I could show you, when you are lonely or in darkness, the astonishing light of your own being.", fa: "ای کاش می‌توانستم نور شگفت‌انگیز وجودت را در تنهایی به تو نشان دهم.", author: "Hafiz", authorFa: "حافظ" },
  { en: "The heart is a thousand-stringed instrument that can only be tuned with love.", fa: "دل سازی هزار تار است که جز با عشق کوک نمی‌شود.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Stay close to anything that makes you glad you are alive.", fa: "نزدیک هر چیزی بمان که از زنده بودنت شادمان شوی.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Fear is the cheapest room in the house. I would like to see you living in better conditions.", fa: "ترس ارزان‌ترین اتاق خانه است. دوست دارم تو را در جایی بهتر ببینم.", author: "Hafiz", authorFa: "حافظ" },
  { en: "I have learned so much from God that I can no longer call myself a Christian, a Muslim, a Hindu, a Buddhist, a Jew.", fa: "از خدا چندان آموخته‌ام که دیگر نمی‌توانم خود را مسیحی، مسلمان، هندو، بودایی یا یهودی بنامم.", author: "Hafiz", authorFa: "حافظ" },
  { en: "The words you speak become the house you live in.", fa: "کلماتی که بر زبان می‌آوری خانه‌ای می‌شوند که در آن زندگی می‌کنی.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Run my dear, from anything that may not strengthen your precious, budding wings.", fa: "عزیزم، از هرچه بال‌های گرانبها و جوانه‌زنت را سست کند بگریز.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Even after all this time, the sun never says to the earth, 'You owe me.' Look what happens with a love like that: it lights the whole sky.", fa: "حتی پس از این همه زمان، خورشید هرگز به زمین نگفت: تو مدیون منی. ببین عشقی چنین چه می‌کند: تمام آسمان را روشن.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Your heart and my heart are very, very old friends.", fa: "دل تو و دل من دوستانی بسیار بسیار کهنه‌اند.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Now is the time to know that all that you do is sacred.", fa: "اکنون وقت آن است بدانی هر آنچه انجام می‌دهی مقدس است.", author: "Hafiz", authorFa: "حافظ" },
  { en: "I am a hole in a flute that the Christ's breath moves through. Listen to this music.", fa: "من سوراخی در نی‌ام که نفس مسیح از آن می‌گذرد. به این نوا گوش بسپار.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Ever since happiness heard your name, it has been running through the streets trying to find you.", fa: "از وقتی شادمانی نامت را شنیده، در کوچه‌ها می‌دود تا تو را بیابد.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Light will someday split you open, even if your life is now a cage.", fa: "نور روزی تو را خواهد شکافت، حتی اگر زندگی‌ات اکنون قفسی است.", author: "Hafiz", authorFa: "حافظ" },
  { en: "What is this precious love and laughter budding in our hearts? It is the glorious sound of a soul waking up.", fa: "این عشق و خنده گرانبها که در دل‌هایمان جوانه می‌زند چیست؟ صدای باشکوه بیدار شدن روح است.", author: "Hafiz", authorFa: "حافظ" },
  { en: "We have not come here to take prisoners, but to surrender ever more deeply to freedom and joy.", fa: "نیامده‌ایم اسیر بگیریم بلکه آمده‌ایم تا هرچه ژرف‌تر تسلیم آزادی و شادی شویم.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Plant seeds of happiness, hope, success, and love; it will all come back to you in abundance.", fa: "بذر شادی، امید، موفقیت و عشق بکار؛ همه با فراوانی به سویت بازمی‌گردند.", author: "Hafiz", authorFa: "حافظ" },
  { en: "I sometimes forget that I was created for joy.", fa: "گاهی فراموش می‌کنم که برای شادی آفریده شده‌ام.", author: "Hafiz", authorFa: "حافظ" },
  { en: "This place where you are right now, God circled on a map for you.", fa: "این جایی که همین الان هستی، خدا روی نقشه برایت دایره کشیده بود.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Join me in the pure atmosphere of gratitude for life.", fa: "در فضای پاک سپاسگزاری از زندگی به من بپیوند.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Grieve not — though the journey of life be bitter, and the end unseen, there is no road which does not lead to an end.", fa: "غم مخور — گرچه سفر زندگی تلخ و پایان ناپیداست، هیچ راهی نیست که به پایانی نرسد.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Last night the moon came dropping its clothes in the street.", fa: "دیشب ماه جامه‌هایش را در کوچه فرو ریخت.", author: "Hafiz", authorFa: "حافظ" },
  { en: "The small man builds cages for everyone he knows, while the sage keeps dropping keys all night long for the beautiful, rowdy prisoners.", fa: "آدم کوچک برای هرکه می‌شناسد قفس می‌سازد، حال آنکه فرزانه تمام شب کلید می‌اندازد برای زندانیان زیبای سرکش.", author: "Hafiz", authorFa: "حافظ" },
  { en: "We are people who need to love because love is the soul's life.", fa: "ما مردمانی هستیم که نیازمند عشقیم زیرا عشق حیات روح است.", author: "Hafiz", authorFa: "حافظ" },
  { en: "If the heart could open the eyes of seeing, it would know the whole world is a book of God.", fa: "اگر دل چشم بینا بگشاید، تمام جهان را کتاب خدا می‌یابد.", author: "Hafiz", authorFa: "حافظ" },
  { en: "Don't surrender your loneliness so quickly. Let it cut more deep.", fa: "تنهایی‌ات را به‌سرعت تسلیم نکن. بگذار عمیق‌تر ببُرد.", author: "Hafiz", authorFa: "حافظ" },

  // ─── Ferdowsi — ~20 quotes ───────────────────────────────────────────
  { en: "The world is a passing thing, but the name of a good man endures forever.", fa: "جهان گذران است ولی نام نیکو جاودان می‌ماند.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Be wise and fill your mind with knowledge, for the ignorant will waste his years.", fa: "توانا بود هر که دانا بود / ز دانش دل پیر برنا بود.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "I suffered much for thirty years, but I revived the Persian language with this poetry.", fa: "بسی رنج بردم در این سال سی / عجم زنده کردم بدین پارسی.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "The wise man should not reveal every secret he holds.", fa: "خردمند نباید هر رازی که دارد فاش کند.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "If you are righteous, you need not fear any power on earth.", fa: "اگر راست‌کردار باشی از هیچ نیرویی بر زمین باک نداری.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Knowledge is a crown on the head of the wise.", fa: "دانش تاجی است بر سر خردمند.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "A man of wisdom is a man of power.", fa: "مرد خردمند مرد توانمند است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Seek knowledge and wisdom, for in them lies the secret of a long and fruitful life.", fa: "دانش و خرد بجوی زیرا در آنها راز زندگی دراز و پربار نهفته است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Fame is the perfume of heroic deeds.", fa: "آوازه عطر کردار پهلوانان است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Do not be in a hurry to take revenge; sit back and wait. Those who eat cold porridge will not burn their lips.", fa: "در انتقام شتاب نکن؛ بنشین و صبر کن. آن‌که آش سرد می‌خورد لبش نمی‌سوزد.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "He who speaks the truth is always at ease.", fa: "آنکه راست می‌گوید همیشه آسوده‌خاطر است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "A man who has no knowledge is like a house without a foundation.", fa: "مردی که دانش ندارد مانند خانه‌ای بی‌پایه است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "The strong arm of a king is justice; without it the throne will collapse.", fa: "بازوی نیرومند شاه عدل است؛ بی آن تخت فرو خواهد ریخت.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Do not sow the seeds of injustice, for you will reap sevenfold.", fa: "تخم بی‌داد نکار که هفت‌چندان درو خواهی کرد.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "Speech is the mirror of the soul; as a man speaks, so is he.", fa: "سخن آینه روح است؛ هرچه گوید همان است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "The world keeps no one forever; be content with what you have.", fa: "جهان هیچ‌کس را نگه نمی‌دارد؛ به آنچه داری خرسند باش.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "An army of deer led by a lion is more fearful than an army of lions led by a deer.", fa: "لشکر آهویی که شیرش فرمانده باشد ترسناک‌تر است از لشکر شیرانی که آهویی فرمانده‌شان باشد.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "When wisdom is at hand, the kingdom rejoices.", fa: "چون خرد در دست باشد، کشور شادمان است.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "No treasure is greater than knowledge.", fa: "هیچ گنجی بزرگ‌تر از دانش نیست.", author: "Ferdowsi", authorFa: "فردوسی" },
  { en: "A land prospers when its people seek knowledge and practice justice.", fa: "سرزمینی آباد می‌شود که مردمش دانش بجویند و داد بورزند.", author: "Ferdowsi", authorFa: "فردوسی" },

  // ─── Omar Khayyam — ~15 quotes ───────────────────────────────────────
  { en: "Be happy for this moment. This moment is your life.", fa: "شاد باش در این لحظه. این لحظه زندگی توست.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "A loaf of bread, a jug of wine, and thou beside me singing in the wilderness.", fa: "نان و پیاله‌ای شراب و تو در کنار من، آوازخوان در بیابان.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "The moving finger writes, and having writ, moves on.", fa: "انگشت نوشته می‌نویسد و چون نوشت بر می‌گذرد.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "Drink wine. This is life eternal. This is all that youth will give you.", fa: "می بنوش که عمر جاودانی این است. حاصل جوانی همین است.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "I came like water and like wind I go.", fa: "چون آب آمدم و چون باد رفتم.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "Dead yesterdays and unborn tomorrows, why fret about them if today be sweet?", fa: "دیروزهای مرده و فرداهای نازاده، چرا غم خوری اگر امروز شیرین است؟", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "When you are dead, your resting-place will be the earth, so while you live be happy.", fa: "چون بمیری آرامگاهت خاک خواهد بود، پس تا زنده‌ای شاد باش.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "Myself when young did eagerly frequent doctor and saint, and heard great argument; but evermore came out by the same door as in I went.", fa: "در جوانی شوق‌مندانه نزد دانشمند و زاهد رفتم و سخنان بزرگ شنیدم؛ اما همواره از همان دری که رفته بودم بیرون آمدم.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "The worldly hope men set their hearts upon turns ashes.", fa: "آرزوی دنیایی که مردم دل بر آن نهند خاکستر می‌شود.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "A hair divides what is false and true.", fa: "مویی حقیقت را از باطل جدا می‌کند.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "Ah, fill the cup! What boots it to repeat how time is slipping underneath our feet.", fa: "آه، پیاله را پر کن! چه سود از تکرار آنکه زمان زیر پایمان می‌لغزد.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "The stars are setting and the caravan starts for the dawn of nothing. Oh, make haste!", fa: "ستارگان غروب می‌کنند و کاروان به سوی بامداد نیستی روان است. آه، بشتاب!", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "There was a door to which I found no key; there was a veil through which I might not see.", fa: "دری بود که کلیدش را نیافتم؛ پرده‌ای بود که از پسش ندیدم.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "You know how little while we have to stay, and once departed, may return no more.", fa: "می‌دانی اندکی بیش در اینجا نمی‌مانیم و چون رفتیم شاید دیگر بازنگردیم.", author: "Omar Khayyam", authorFa: "عمر خیام" },
  { en: "One thing is certain: this life flies. One thing is certain: the rest is lies.", fa: "یک چیز مسلم است: این عمر می‌گذرد. یک چیز مسلم است: باقی دروغ است.", author: "Omar Khayyam", authorFa: "عمر خیام" },

  // ─── Attar — ~10 quotes ──────────────────────────────────────────────
  { en: "If the eye of the heart is open, in each atom there will be a hundred secrets.", fa: "اگر چشم دل باز باشد در هر ذره‌ای صد راز نهان است.", author: "Attar", authorFa: "عطار" },
  { en: "The ocean can be contained in a dewdrop when your heart is the vessel.", fa: "اقیانوس در قطره شبنمی جا می‌گیرد وقتی دلت ظرف باشد.", author: "Attar", authorFa: "عطار" },
  { en: "If you cannot smell the fragrance, do not come into the garden of love.", fa: "اگر عطر را نمی‌شنوی به باغ عشق میا.", author: "Attar", authorFa: "عطار" },
  { en: "Know that the world is a mirror from head to foot; in every atom a hundred blazing suns.", fa: "بدان که جهان آینه‌ای است سرتاپا؛ در هر ذره‌ای صد خورشید تابان.", author: "Attar", authorFa: "عطار" },
  { en: "I will not tire of seeking, even if the journey takes my entire life.", fa: "از جستجو خسته نمی‌شوم حتی اگر تمام عمرم صرف راه شود.", author: "Attar", authorFa: "عطار" },
  { en: "Until you've found pain, you won't reach the cure.", fa: "تا درد نیافته‌ای به درمان نمی‌رسی.", author: "Attar", authorFa: "عطار" },
  { en: "The journey of a thousand miles begins with the turning of the heart.", fa: "سفر هزار فرسنگی با چرخیدن دل آغاز می‌شود.", author: "Attar", authorFa: "عطار" },
  { en: "When you see the face of the Beloved in the mirror of the heart, you will understand that you have never been apart.", fa: "وقتی چهره معشوق را در آینه دل ببینی درمی‌یابی که هرگز جدا نبوده‌ای.", author: "Attar", authorFa: "عطار" },
  { en: "Whoever has not tasted the bitterness of patience will never enjoy the sweetness of wisdom.", fa: "هرکه تلخی صبر را نچشیده باشد شیرینی خرد را نخواهد چشید.", author: "Attar", authorFa: "عطار" },
  { en: "Purify your heart before you embark on the journey, for only a clean mirror reflects the light.", fa: "دل را پاک کن پیش از آنکه به سفر روی، زیرا تنها آینه‌ای پاک نور را بازتاب می‌دهد.", author: "Attar", authorFa: "عطار" },

  // ─── Nizami — ~10 quotes ─────────────────────────────────────────────
  { en: "Generosity is giving more than you can, and pride is taking less than you need.", fa: "سخاوت آن است که بیش از توان بدهی و غرور آن است که کمتر از نیاز بگیری.", author: "Nizami", authorFa: "نظامی" },
  { en: "A treasure trove of gold is not worth a handful of knowledge.", fa: "خزانه‌ای پر از طلا به اندازه مشتی دانش نمی‌ارزد.", author: "Nizami", authorFa: "نظامی" },
  { en: "Love that is not rooted in the spirit withers like a flower cut from its stem.", fa: "عشقی که در روح ریشه ندارد مانند گلی بریده از ساقه‌اش پژمرده می‌شود.", author: "Nizami", authorFa: "نظامی" },
  { en: "The wise one waters the root, not the branches.", fa: "خردمند ریشه را آب می‌دهد نه شاخه‌ها را.", author: "Nizami", authorFa: "نظامی" },
  { en: "Beauty without virtue is a flower without fragrance.", fa: "زیبایی بدون فضیلت گلی بدون عطر است.", author: "Nizami", authorFa: "نظامی" },
  { en: "When justice prevails, even the smallest flame can illuminate the world.", fa: "وقتی عدالت حکم‌فرما باشد حتی کوچک‌ترین شعله می‌تواند جهان را روشن کند.", author: "Nizami", authorFa: "نظامی" },
  { en: "The secret of happiness lies in looking at all the wonders of the world and never forgetting the two drops of oil on the spoon.", fa: "راز خوشبختی در نگریستن به شگفتی‌های جهان است بی‌آنکه دو قطره روغن روی قاشق را فراموش کنی.", author: "Nizami", authorFa: "نظامی" },
  { en: "In the garden of love, thorns are as necessary as roses.", fa: "در باغ عشق خارها به اندازه گل‌ها ضروری‌اند.", author: "Nizami", authorFa: "نظامی" },
  { en: "He who has learned to bear suffering patiently has learned the secret of life.", fa: "آنکه آموخته رنج را صبورانه تحمل کند، راز زندگی را آموخته.", author: "Nizami", authorFa: "نظامی" },
  { en: "Choose your words wisely, for they will echo through eternity.", fa: "سخنانت را خردمندانه برگزین، زیرا تا ابد بازتاب خواهند داشت.", author: "Nizami", authorFa: "نظامی" },
];
